apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}" 
          ports:
            - containerPort: 5000
          env:
          - name: CONNECTION_URL
            value: "mongodb://mongo-0.mongodb-service:27017/test"
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: LoadBalancer
  selector:
    app: server
  ports:
    - port: 5000
      targetPort: 5000
